### ISSUE TITLE
Changes to work out of the box with ember simple auth

### ISSUE THREAD

**Issue by alexjp** [manukall/phoenix_token_auth#19]
Hi,

Created a fork : https://github.com/alexjp/phoenix_token_auth , that more or less only adds username, disables email and works with what ember simple auth expects.
Its just a quick solution for a need i have in a project.
Hope its okay with you. Also if you want, i can do a less intrusive change and a pull request.

Thanks !

**Comment by manukall** [comment]
hi @alexjp,
this is great! i didn't really look at your fork yet, but do you think there is a nice way to integrate it?

**Comment by alexjp** [comment]
Hi,

I have been thinking on a less intrusive change. I think there is a way, I will think more on how to do it.

EmberSimpleAuth passes the grant type (password), so i guess, that the only real thing needed is a sessions controller function that uses it.

I will try to do again using this project, but being the less intrusive i can.

If i may, the planning is this:
- update deprecations for phoenix 0.14
- add config option to skip email
- add path if grant_type is password, to use username ( maybe create optional field ) and return json like ember simple auth expects.
- add tests, testing the username login and response.

Thanks again for the phoenix_token_auth package !!

**Comment by manukall** [comment]
Hey @alexjp,

sorry it took me so long. are you still interested?

you're plan sounds pretty solid, although I'm not sure I fully understand it:
- will the config option to skip email disable sending emails? if so, I guess we will also need to "turn off" the confirmation requirement, or at least provide a way to do so. if the user does not get a confirmation, they will not be able to confirm their account.
- I don't quite get the next part. do you want to add another route for authenticating by username? I think I would prefer making the current route configurable. maybe we provide a config option like `user_finder: MyUser, :find_by_email`, that would then be expected to fetch the user from the database. The authenticator could the use that to check the password. Would that make sense? We would also need to change the params the session controller expects, but I think we should nest them anyway. (like `%{user: %{email: "test@example.com", password: "12345678"}}`. what do you think?
- Do you think we could go the same route for the response? Provide a config that points to a method which we then expect to return the response data?

sorry again that it took me so long.

**Comment by alexjp** [comment]
Very interested ! :)
- Yes, i have made it in my fork to allow this, to "auto confirm". Still, i need to think about a cleaner way to do it.
- Currently simple-ember-auth sends grant_type=password. We can use this parameter to check and either use by email or by username.
- Yes, we should go that way also.

My goals:
There are two major "agendas" i have with my fork: 
- complete ember-simple-auth support out of the box ( as I am devoted to emberJS in frontend development )
- what my company projects usually needs in terms of authentication. ( Although not very correct, most of my projects, there is an admin that manages or we manage the login and authorization of users )

Both of these "agendas" are highly personal. But i would like to at least have simple-ember-auth support.

**Comment by alexjp** [comment]
Did a new pull request from scratch.
I did alot less changes than before. Also, should be drop in replacement ( i removed the changes to the user model tokens)

It should be much cleaner and easy to understand what i changed.

There should be a way to detect username/email registration and identification much better than what i use. Maybe elixir magic.
