### ISSUE TITLE
Phoenix 0.14 and phoenix_token_auth 0.2.0 - Error: protocol Phoenix.Param not implemented for []

### ISSUE THREAD

**Issue by ACPK** [manukall/phoenix_token_auth#25]
I just updated Phoenix and Phoenix_token_auth but get the following error when trying to create the user via our API.

```
[error] #PID<0.399.0> running CallRedApp.Endpoint terminated
Server: 16c1026536f.a.passageway.io:80 (http)
Request: POST /v1/users
** (exit) an exception was raised:
    ** (Protocol.UndefinedError) protocol Phoenix.Param not implemented for []
        (phoenix) lib/phoenix/param.ex:122: Phoenix.Param.Any.to_param/1
        (call_red_app) web/router.ex:1: CallRedApp.Router.Helpers.page_path/4
        (call_red_app) web/router.ex:1: CallRedApp.Router.Helpers.page_url/4
        (call_red_app) web/mailers/mailer.ex:10: CallRedApp.Mailer.welcome_body/2
        lib/phoenix_token_auth/mailer.ex:30: PhoenixTokenAuth.Mailer.send_welcome_email/2
        (ecto) lib/ecto/pool.ex:292: Ecto.Pool.with_rollback/2
        (ecto) lib/ecto/adapters/sql.ex:567: Ecto.Adapters.SQL.transaction/8
        (ecto) lib/ecto/pool.ex:244: Ecto.Pool.outer_transaction/6
```

**Comment by manukall** [comment]
it looks like you are giving an empty list (`[]`) to `page_url` inside the `CallRedApp.Mailer.welcome_body/2
` function. can you paste that method?

**Comment by ACPK** [comment]
Here's my mailer below. I'm using the sample app and don't believe I've made a change to the signup functionality other than add a few params.

```
defmodule CallRedApp.Mailer do
  alias CallRedApp.Router
  alias CallRedApp.Endpoint
  @behaviour PhoenixTokenAuth.MailingBehaviour

  def welcome_subject(user), do: "Hello #{user.email}"
  def welcome_body(user, token) do
    """
    Please follow the link below:
    #{Router.Helpers.page_url(Endpoint, :index)}#/users/#{user.id}/confirm/#{token}
    """
  end

  def password_reset_subject(user), do: "Hello #{user.email}"

  def password_reset_body(user, reset_token) do
    """
    Please follow the link below:
    #{Router.Helpers.page_url(Endpoint, :index)}#/users/#{user.id}/reset_password/#{reset_token}
    """
  end

  def new_email_address_subject(_user), do: "Please confirm your email address"

  def new_email_address_body(user, confirmation_token) do
    """
    Please follow the link below:
    #{Router.Helpers.page_url(Endpoint, :index)}#/users/#{user.id}/confirm/#{confirmation_token}
    """
  end

end
```

**Comment by manukall** [comment]
i'm kind of lost here. did you restart the server and try again?

also, could you try `CallRedApp.Router.Helpers.page_url(CallRedApp.Endpoint, :index)` in iex?

**Comment by ACPK** [comment]
I've restarted the sample app. Want me to do a PR with the updates that break it?

**Comment by manukall** [comment]
yes, let's try that.

**Comment by manukall** [comment]
@ACPK what happened here? did you delete your last comment? is the issue solved for you?

**Comment by ACPK** [comment]
@manukall  - Nope and I've also tried adding it to a totally new app with 0.14.0. Should the module work with .14 as here's the app? https://github.com/ACPK/phoenix_token_api_example

**Comment by manukall** [comment]
yes. how can i reproduce the error in the repo you linked?

**Comment by ACPK** [comment]
@manukall - I'm testing doing a POST to /api/v1/users. With a "application/json" content-type, I'm submitting the parameters below.

```
{
   "user": {
      "email": "adfjkadfjk@kjakjdf.com",
      "password": "Password"
   }
}
```

**Comment by manukall** [comment]
i don't think the way you defined your Page#index route works. That is where the error comes from. It expects a parameter, because you have the line `get "/:page", PageController, :index` in your router.
you could change the mailer to link to `Router.Helpers.page_url(Endpoint, :index, "")`, if that makes sense in your app.

**Comment by ACPK** [comment]
@manukall - I tried that along with just getting rid of the "confirmation link" in the email to test it, but get"(MatchError) no match of right hand side value: {:error, :bad_fetch, :no_scheme}"

If I remove the line get "/:page", PageController, :index, I get the error protocol Enumerable not implemented for "".

**Comment by manukall** [comment]
i had that as well. mailgun requires you to provide the full domain now. it looks something like `MAILGUN_DOMAIN=https://api.mailgun.net/v3/xxxxxxxxxxxxx`
