### ISSUE TITLE
Recommend tagging releases so they're listed in Github.

### ISSUE THREAD

**Issue by ACPK** [manukall/phoenix_token_auth#26]

**Comment by manukall** [comment]
can you elaborate on that? all i found was https://help.github.com/articles/creating-releases/, which uses git tags and seems a bit complicated. i kind of enjoy the simple way hex provides to do releases.

**Comment by ACPK** [comment]
Github says they're 0 releases - https://github.com/manukall/phoenix_token_auth/releases.

Example of releases: https://github.com/lynndylanhurley/devise_token_auth/releases

**Comment by manukall** [comment]
i think you need to do what is described in the first link to get the github releases. for now, we still release too often and i'm a bit too lazy for the overhead. i'll consider again when the library becomes more stable.
