### ISSUE TITLE
Can't require custom paramaters

### ISSUE THREAD

**Issue by LeeroyDing** [manukall/phoenix_token_auth#27]

**Comment by manukall** [comment]
please give a bit more info. what are you trying to do and what error do you receive?

**Comment by LeeroyDing** [comment]
I'm trying to add a required field (like, "team name" in slack), so that any registering user is required to have a team name. There seems to be no way of doing that without modifying this library's source code.

**Comment by LeeroyDing** [comment]
FYI the default implementation of Phoenix's mix task (`phoenix.gen.model`) is to add this function in each model, and use them to generate the corresponding changeset.

```
def changeset(model, params \\ :empty) do
  model
  |> cast(params, @required_fields, @optional_fields)
end
```

I would suggest the same approach.

**Comment by manukall** [comment]
ah ok. got you.

for now you could just write your own implementation of the registration action and add a route to that instead of the one from this library. you could still add routes to the other actions. see https://github.com/manukall/phoenix_token_auth/blob/master/lib/phoenix_token_auth.ex

**Comment by LeeroyDing** [comment]
Let's go to PR #28 and see what we can do.
