### ISSUE TITLE
Security Recommendations

### ISSUE THREAD

**Issue by ACPK** [manukall/phoenix_token_auth#3]
Awesome job and hopefully this project will gain similar traction to the Ruby Token Gem (https://github.com/lynndylanhurley/devise_token_auth).

For security reasons:
1. The API should update the auth token for each request, except for a 5 second buffer for batch processes (see: https://github.com/lynndylanhurley/devise_token_auth#about-token-management).
2. Besides the token, the header should pass along the client (enables the use of multiple simultaneous sessions on different clients), expiry, and uid.
3. Signing out will invalidate the user's authentication token for the client.

**Comment by manukall** [comment]
The concept here is a bit different, more like JWT (see http://jwt.io/). We basically sign the user's id with a (global per app) secret key and send that as the token to the user. This means, we don't store a token per user in the database. 

This also means we can not invalidate a single user's token. We can only change the global secret and thus invalidate all tokens. Given that, I can't think of a way of implementing point 1 and 3.

Regarding your second point, the token itself already contains the uid and an expiry date.

**Comment by ACPK** [comment]
So if a user changes their password for security reasons, it wouldn't invalidate the current token that's being used by an iOS app, OS X app, and / or web app?

**Comment by manukall** [comment]
No, it wouldn't. This is how JWT works.

I totally see your point though. I can think of a few possible ways to work around this:
- Have a very short expiration period (probably too inconvenient)
- Store the token as a database field for each user and check that on each request
- Store a "version" field on the users and encode that also in the tokens. Then when the user changes their password, you can increase the version and make the token invalid.

**Comment by ACPK** [comment]
@manukall  -Thanks for this and the second bullet seems to be Github's approach to using JWT for their API.

A password reset would clear the "tokens" database field (text), and I like how Github still has a unique token for each client with a JWT setup. A potential example for saving a device token for each client: 

{"S5tufdajh34jh3JH3hj4hj3vRtPAQ"=>{"token"=>"$2a$10$BhCPJpo.dKW.fOEandfadjHdhfGpe.uuoqi/xF8yxwe", "expiry"=>1428014576}},

https://auth0.com/blog/2014/12/02/using-json-web-tokens-as-api-keys/

Github: https://github.com/settings/applications#personal-access-tokens

Hence, a sign out could now deactivate the token for a specific client.

**Comment by manukall** [comment]
@ACPK Thanks for the links. This looks good and I think it should definitely be on the roadmap.

**Comment by manukall** [comment]
@ACPK https://github.com/manukall/phoenix_token_auth/pull/4 stores user tokens in the database and deletes them on logout. what do you think?

**Comment by ACPK** [comment]
@manukall I'm in the middle of a deadline right now, but I'll take a look this weekend if that works for you.

**Comment by ACPK** [comment]
@manukall Big thanks your most recent feature which clears the tokens!

**Comment by manukall** [comment]
@ACPK i think i have to disappoint you. we didn't change anything about clearing tokens in the last release
