### ISSUE TITLE
Current locale in mailer

### ISSUE THREAD

**Issue by OpakAlex** [manukall/phoenix_token_auth#31]
Hi, we need pass current locale to mailer. Can we proxy pass to mailer methods `conn`?

**Comment by OpakAlex** [comment]
@manukall what are you think?

**Comment by manukall** [comment]
i think passing conn to the mailer methods is actually a pretty good idea. would you be willing to create a PR for that?

**Comment by OpakAlex** [comment]
@manukall ok, i will try :)
