### ISSUE TITLE
Some routes changes

### ISSUE THREAD

**Issue by OpakAlex** [manukall/phoenix_token_auth#32]
``` elixir
 defmacro mount do
    quote do
      post  "users",                 PhoenixTokenAuth.Controllers.Users, :create
      post  "users/:id/confirm",     PhoenixTokenAuth.Controllers.Users, :confirm
      post  "sessions",              PhoenixTokenAuth.Controllers.Sessions, :create
      delete  "sessions",            PhoenixTokenAuth.Controllers.Sessions, :delete
      post  "password_resets",       PhoenixTokenAuth.Controllers.PasswordResets, :create
      post  "password_resets/reset", PhoenixTokenAuth.Controllers.PasswordResets, :reset
      get   "account",               PhoenixTokenAuth.Controllers.Account, :show
      put   "account",               PhoenixTokenAuth.Controllers.Account, :update
    end
  end
```

I thinks, we need change some url, for example:
`post  "sessions"` it must be `post "users/sign_in"`
`delete "sessions" it must be 'delete' "users/sign_out"`

What are you think?

**Comment by OpakAlex** [comment]
@manukall :)

**Comment by manukall** [comment]
hey @OpakAlex 
i don't see the reason to change it. what's the use case or problem you're running into?

**Comment by alexjp** [comment]
I may add that i dont like very much that there are 

```
      post  "users",                 PhoenixTokenAuth.Controllers.Users, :create
      post  "users/:id/confirm",     PhoenixTokenAuth.Controllers.Users, :confirm
```

This takes for granted that the "user" model is called users.

I successfully managed to make it use the "Account" model ( taken idea from your use of account model )

**Comment by OpakAlex** [comment]
@alexjp Account model it's not user. In real projects you have User and Account. I think we need do get request to users, not to accounts.

**Comment by manukall** [comment]
it's pretty easy to just define your own routes. just instead of putting `PhoenixTokenAuth.mount` into your router define them manually as that macro would.

**Comment by alexjp** [comment]
@manukall definitly.
Later at night, can i do a pull request to the documentation ? "Customizing routes?"

**Comment by manukall** [comment]
@alexjp that would be extremely great :smiley:

**Comment by OpakAlex** [comment]
+1
