### ISSUE TITLE
Updated Module in APP:  undefined function: CallRedApp.Mailer.welcome_subject/2

### ISSUE THREAD

**Issue by ACPK** [manukall/phoenix_token_auth#41]
When I pulled the latest changes, I now get "undefined function: CallRedApp.Mailer.welcome_subject/2". Do I need to change some mail paths as I'm using the ones from the older Phoenix_token_auth sample app?

Here's what is showing up in the logs:

```
web/mailers/mailer.ex:1: warning: undefined behaviour function new_email_address_body/3 (for behaviour PhoenixTokenAuth.MailingBehaviour)
web/mailers/mailer.ex:1: warning: undefined behaviour function new_email_address_subject/2 (for behaviour PhoenixTokenAuth.MailingBehaviour)
web/mailers/mailer.ex:1: warning: undefined behaviour function password_reset_body/3 (for behaviour PhoenixTokenAuth.MailingBehaviour)
web/mailers/mailer.ex:1: warning: undefined behaviour function password_reset_subject/2 (for behaviour PhoenixTokenAuth.MailingBehaviour)
web/mailers/mailer.ex:1: warning: undefined behaviour function welcome_body/3 (for behaviour PhoenixTokenAuth.MailingBehaviour)
web/mailers/mailer.ex:1: warning: undefined behaviour function welcome_subject/2 (for behaviour PhoenixTokenAuth.MailingBehaviour)
web/mailers/mailer.ex:3: warning: unused alias Endpoint
```

It seems like these are the changes (https://github.com/manukall/phoenix_token_auth/commit/7872e567c63c18d5d8798d7c5f52631e5d910fac) which require the mailers to be changes. Any suggestions would be appreciated!

**Comment by manukall** [comment]
the mailer methods need to take two parameters now. the second one is the connection. i've added a changelog that will list breaking changes like that.

btw, i've added a badge-link to my pet project projecttalk.io at the top of the readme. if you wouldn't mind being a beta-tester you could post things like this there instead...
