### ISSUE TITLE
Question : How the confirmation link can be a post ?

### ISSUE THREAD

**Issue by plu9in** [manukall/phoenix_token_auth#54]
When someone clicks on a link contained into an email, it triggers a get on the server and not a post, doesn't it ? So, in the phoenix_token_auth.ex, why do we have to put a post : 
      # Confirm url
      post  "users/:id/confirm",     PhoenixTokenAuth.Controllers.Users, :confirm

How can the email send something via json ? I don't get it.

**Comment by manukall** [comment]
As phoenix_token_auth is meant to be used in backend apis, it is expected that something sits between itself and the user. You could for example have a Javascript app that you link to from the email and that would then do the POST request to the backend api.

**Comment by plu9in** [comment]
Ah ok. Thanks. I am using it directly for a mobile app backend. I will transform it to a get then.
